version: "3"

services:
  next:
    build:      
      context: .
      dockerfile: ./frontend/Dockerfile
    container_name: next-container
    hostname: next-server
    tty: true
    environment:
      - NODE_ENV=DEVELOPMENT
      - PORT=3000
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend/app:/usr/src/app
    ports:
      - 3000:3000
